name: blog-build-ci
on: 
  push:
    branches:
      - master
      
jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
  build:
    needs: init
    steps:
      run: ./deploy.sh
  
