name: blog-build-ci
on: 
  push:
    branches:
      - master
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 拉取 github 仓库代码
      - uses: actions/checkout@v3
      - uses: webfactory/ssh-agent@v0.7.0
          with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      # 设定 node 环境
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: 构建
        run: ./deploy.sh
  
